import { defineRouteMiddleware } from '@astrojs/starlight/route-data';

type Route = App.Locals['starlightRoute'];
type SidebarEntry = Route['sidebar'][number];
type SidebarLink = Extract<SidebarEntry, { type: 'link' }>;
type PrevNextConfig = Route['entry']['data']['prev'];

const TAGS_HREF = '/tags/';
const PROJECTS_DIR = 'projects';

// Flatten the sidebar depth-first into its links, in display order.
const flatten = (entries: SidebarEntry[]): SidebarLink[] =>
	entries.flatMap((entry) => (entry.type === 'group' ? flatten(entry.entries) : [entry]));

// Mirrors Starlight's `applyPrevNextLinkConfig` so frontmatter `prev`/`next` still apply
// (pagination is enabled site-wide, Starlight's default).
const applyConfig = (link: SidebarLink | undefined, config: PrevNextConfig): SidebarLink | undefined => {
	if (config === false) return undefined;
	if (config === true || config === undefined) return link;
	if (typeof config === 'string') return link ? { ...link, label: config } : undefined;
	if (link) return { ...link, label: config.label ?? link.label, href: config.link ?? link.href, attrs: {} };
	if (config.link && config.label) {
		return { type: 'link', label: config.label, href: config.link, isCurrent: false, badge: undefined, attrs: {} };
	}
	return undefined;
};

// Readable labels for folder groups (at any depth) in the autogenerated sidebar.
const groupLabels: Record<string, string> = {
	css: 'CSS',
	'design-systems': 'Design systems',
	ebooks: 'Ebooks',
	files: 'Files',
	html: 'HTML',
	images: 'Images',
	interaction: 'Interaction',
	javascript: 'JavaScript',
	'machine-learning': 'Machine learning',
	practices: 'Practices',
	projects: 'Projects',
	react: 'React',
	'react-native': 'React Native',
	reader: 'Reader',
	riftcards: 'Riftcards',
	scrolling: 'Scrolling',
	security: 'Security',
	storage: 'Storage',
	svelte: 'Svelte',
	testing: 'Testing',
	text: 'Text',
	tooling: 'Tooling',
	typescript: 'TypeScript',
	'ui-patterns': 'UI patterns',
};

const prettify = (folder: string) =>
	groupLabels[folder] ?? folder.charAt(0).toUpperCase() + folder.slice(1).replace(/-/g, ' ');

// Relabel folder groups at every depth. Groups under `projects/<project>` (and deeper) start
// collapsed; Starlight still opens any group that contains the current page.
const relabel = (entries: SidebarEntry[], path: string[] = []) => {
	for (const entry of entries) {
		if (entry.type !== 'group') continue;
		const groupPath = [...path, entry.label];
		entry.label = prettify(entry.label);
		if (groupPath[0] === PROJECTS_DIR && groupPath.length > 1) entry.collapsed = true;
		relabel(entry.entries, groupPath);
	}
};

// Adjust the default autogenerated sidebar without replacing it:
// home link first, readable group labels, projects after the general notes, and an "All tags" link last.
export const onRequest = defineRouteMiddleware((context) => {
	const { sidebar } = context.locals.starlightRoute;

	// Find the projects group by its raw folder name before relabelling.
	const projectsIndex = sidebar.findIndex((entry) => entry.type === 'group' && entry.label === PROJECTS_DIR);
	relabel(sidebar);

	if (projectsIndex > -1) {
		const [projects] = sidebar.splice(projectsIndex, 1);
		sidebar.push(projects!);
	}

	const homeIndex = sidebar.findIndex((entry) => entry.type === 'link' && entry.href === '/');
	if (homeIndex > 0) {
		const [home] = sidebar.splice(homeIndex, 1);
		sidebar.unshift(home!);
	}

	const href = TAGS_HREF;
	sidebar.push({
		type: 'link',
		label: 'All tags',
		href,
		isCurrent: context.url.pathname.startsWith(href),
		badge: undefined,
		attrs: {},
	});

	// Starlight computed pagination before this reorder, so rebuild it from the final order.
	// The "All tags" link is excluded; pages not in the list (e.g. tag pages) get none.
	const links = flatten(sidebar).filter((link) => link.href !== TAGS_HREF);
	const current = links.findIndex((link) => link.isCurrent);
	const { prev, next } = context.locals.starlightRoute.entry.data;
	context.locals.starlightRoute.pagination = {
		prev: applyConfig(current > 0 ? links[current - 1] : undefined, prev),
		next: applyConfig(current > -1 ? links[current + 1] : undefined, next),
	};
});
