/**
 * Allowed tag vocabulary. The docs schema only accepts these values, so a page
 * using a tag that is not listed here fails the build. Add new tags here first.
 */
export const TAGS = [
	'accessibility',
	'architecture',
	'bundling',
	'cache-api',
	'canvas',
	'cascade-layers',
	'color-scheme',
	'components',
	'csp',
	'css',
	'custom-properties',
	'dependency-cruiser',
	'design-systems',
	'design-tokens',
	'dialog',
	'dokseo',
	'domain-driven-design',
	'drizzle',
	'error-handling',
	'expo',
	'files',
	'focus',
	'foliate-js',
	'fonts',
	'git',
	'hashing',
	'html',
	'i18n',
	'iframes',
	'images',
	'indexeddb',
	'javascript',
	'keyboard',
	'layout',
	'machine-learning',
	'mobile',
	'motion',
	'naming-conventions',
	'ocr',
	'onnx',
	'opfs',
	'pdfjs',
	'playwright',
	'pointer-events',
	'popover',
	'project-structure',
	'react',
	'react-native',
	'rifty',
	'safari',
	'scope',
	'scrolling',
	'security',
	'selection',
	'specificity',
	'sqlite',
	'storage',
	'svelte',
	'svelte-5',
	'sveltekit',
	'tanstack-query',
	'testing',
	'theming',
	'transformers-js',
	'typescript',
	'typography',
	'ui-patterns',
	'unicode',
	'virtualization',
	'vite',
	'vitest',
	'web-workers',
	'webgpu',
	'zip',
] as const;

export type Tag = (typeof TAGS)[number];

export const tagHref = (tag: string) => `/tags/${tag}/`;
